apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-deploy
  name: go-deploy
  namespace: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-deploy
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-deploy
    spec:
      containers:
      - image: trahulprabhu38/go-web-app:v1
        name: go-web-app
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

          
status: {}

