apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-svc
  name: go-svc
  namespace: go-web-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-svc
  type: ClusterIP
status:
  loadBalancer: {}
